global using Microsoft.Extensions.Configuration;
global using NUnit.Framework;
global using NUnit.Framework.Internal;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Support.UI;
global using OpenQA.Selenium.Interactions;
global using Utilities;